# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f5f56c32009d4bb6b64be2720e40130b2d116ada8539c981ef0013c3085a8a607a47c5b83397464b285bbf7a163c5e0f585cccebc0a3d94acd49506010f92b0

test:
  secret_key_base: fd495ccfb3542b70758fc8e1bd093a5ed70b6452418d25824fe6f58d123aa7a3bb12c58a0727709c7ba824c40e74f23446d7cc53ff39b21ebb926749617711d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
